### PR TITLE
Gracefully handle single atoms.

### PR DESCRIPTION
**Pull request by psi-rking**
If a single-atom is submitted as the molecular system, then compute an energy.  Put the energy in the trajectory and energies array in the returned json file, but set the 'success' to False.  Also add message to log file about what is going on.  Added test to demonstrate this.

### CODE REVIEW

**Review by AlexHeide — CHANGES_REQUESTED** [review]
This looks like the right approach to me, but only works when using optking's built in optimization driver. If we move this to `OptimizationManager.start_step()` everything should use this auto-magically.

**Comment by AlexHeide** [comment]
Any `OptErrors` that get raised should be caught and processed by `opt_error_handler` which eventually calls `finish` to produce a `OptimizationResult` the same way you're doing generating one. Unless a user directly instantiates an` OptimizationAlgorithm`, all the interfaces should call `start_step`.

**Comment by psi-rking** [comment]
But do we have any relevant tests that when run on an atom would be a solid
generic test?

I'm not a big fan of overlapping exceptions, but I was also unsure if we
could get the "successful error" through the finish.  But now that I've
worked on it and look at it again, it seems an OptErr (as opposed to an
AlgErr) may do the trick - at least in optimize...  I'll give it a try.

**Comment by AlexHeide** [comment]
I'm not totally sure what you mean by overlapping exceptions. We could definitely add more specific exceptions instead of relying on the broad Opt and Alg Error types.

**Comment by psi-rking** [comment]
OK.  That's not quite right as opt_input needs an "initial_molecule", and "input_specification" but I'll do something like that.

**Review by AlexHeide — APPROVED** [review]
LGTM!

**Pull request merged**
