### PR TITLE
move tests inside module

### LINKED ISSUE #60: move tests directory
I suggest you move tests from `<top-level>/tests` into `<top-level>/optking/tests`. That way, the tests will install alongside the python package, and `pytest optking/` can work on an installed package. That'll make the conda package more testable.

### PR DESCRIPTION
**Pull request by loriab**
fixes #60 

this isn't vital, but it's more conventional for a pure-python project.

### CODE REVIEW

**Comment by psi-rking** [comment]
Lori, Alex and I just went through all that reformatting with black v.20.  Are you using a different standard?

**Comment by loriab** [comment]
Ok, adding the `tests/__init__.py` seems to have done the trick for getting the conda package testable. Python packaging is beyond my grasp.

**Comment by loriab** [comment]
This I think is good to go. You have a conda package. https://anaconda.org/psi4/optking/files Do you know where to go to turn off the travis required status in GH? I've had to do that lately.

**Comment by psi-rking** [comment]
Not off the top of my head, before looking.  Is it hard to find?

**Comment by loriab** [comment]
You go to Settings -> Branches -> master -> edit . and then clear the checkbox(es) from Travis and add checks for the CI.

**Review by AlexHeide — APPROVED** [review]
Awesome! Thank you for your setting up all this packaging stuff for us.

**Comment by psi-rking** [comment]
Thanks. I've got the chance to read through this pull request now.

**Comment by psi-rking** [comment]
Blank __init__.py.   Clever.

**Pull request merged**
