### PR TITLE
Updates conda environments for CI

### PR DESCRIPTION
**Pull request by AlexHeide**
Remove references to old psi4 conda channel
Update dftd3 packages used for testing

### CODE REVIEW

**Review by psi-rking — APPROVED** [review]

**Comment by psi-rking** [comment]
@AlexHeide , Are you ready to merge?

**Comment by AlexHeide** [comment]
Upgrading to codecov v4 and adopting the auth tokens seems to have worked. Issue seems related to: https://github.com/codecov/engineering-team/issues/1574

Shall we can close this PR in favor of Lori's and add the codecov updates there?

**Comment by loriab** [comment]
> Shall we can close this PR in favor of Lori's and add the codecov updates there?

I can confirm that `dftd3-python` pkg brings `simple-dftd3` as a dep. I noticed locally that you might be looking for `which dftd3` somewhere, and that should probably get updated to `which s-dftd3` or both.

**Comment by loriab** [comment]
I'm also glad to rebase mine after this is merged.

**Comment by AlexHeide** [comment]
@loriab Do you remember the context where you ran into optking trying to check for dftd3 or execute dftd3? I can't find any references in optking at least to dftd3 outside of the conda-envs.

**Pull request merged**
