### PR TITLE
use qcelemental

### PR DESCRIPTION
**Pull request by loriab**
- [x] use qcelemental for periodic table, physical constants, and covalent radii
- Note that this involves a codata2011 --> codata2014 update to bohr2angstom which psi4 has already made.
- [x] adds MolSSI tools for setting up environments that simplifies `.travis.yml`
- [x] adds versioning tool "versioneer". to mint a new version, make a git tag `git tag -a v0.2.0 -m "v0.2.0"` and push it to github `git push origin v0.2.0`

### CODE REVIEW

**Comment by loriab** [comment]
Hi @psi-rking, it looks like I have write access to the optking repo. One of the most valuable features of the pull request (PR) process, in my opinion, is that it allows you as the the primary maintainer to keep track of what changes have been made. Therefore, I think it'd be good if either you merged PRs when checks pass and you like the contents _or_ you leave approving reviews ("files changed" tab, "review changes" button) to show you've looked it over then I'll merge when ready. You're welcome to just sign-off on the PR or make multiple per-line comments, like we do in psi4.

In my view, both #22 and #23 are ready for merge.

**Comment by psi-rking** [comment]
OK, I'll merge the commits myself.

**Comment by psi-rking** [comment]
All looks good to me, though I didn't spend time on the versioneer stuff.

**Comment by loriab** [comment]
That's fine. The versioneer stuff is all generated code and proven across hundreds of projects.

**Pull request merged**
