### PR TITLE
Misc. IRC Fixes

### PR DESCRIPTION
**Pull request by JonathonMisiewicz**
This is _not_ ready for merge and is being PRd solely for convenience of @AlexHeide and for general information.

I'm trying to get an IRC but have been running into some bugs. So far, I've found and solved:
* When redundant coordinates are used, the IRC will have near-zero eigenvalues in the G matrix. These must be removed in inverse functions.
* Some numerical noise "eigenvalues" were not being removed, leading to small negative eigenvalues that should have been removed. The threshold for removal is now less strict.
* A bug in the solution of the Lambda equations has been fixed. After the coarse-graining step, Lambda could become approx -500 due to a mistake with setting the previous lambda in the bisection stage. That has been corrected.

The IRC code is still too buggy for my purposes. For some reason, the steps when trying to converge a point on a path oscillate. Sometimes the oscillations are damped, other times not. (The IRC promptly fails.) When I have that solved, I'll add it to the PR.

### CODE REVIEW

**Comment by JonathonMisiewicz** [comment]
I'm still having some issues with the IRC code terminating prematurely, but changes to the IRC logic that large require the attention of somebody who knows the algorithm a lot better than I do. This PR is done, in my judgment.

**Comment by psi-rking** [comment]
LGTM.  Obviously, we had never tried the IRC with larger molecules and redundant coordinates.  You appear to have fixed that problem at least.

**Comment by psi-rking** [comment]
@JonathonMisiewicz , now that I'm working on optking again, we can get this integrated.  Would you like to rebase and tidy up (Alex Heide changed some function names), and I will merge it?  Or if you would prefer, I could just manually incorporate these fixes into a new pull request and take care of it myself.

**Comment by JonathonMisiewicz** [comment]
@psi-rking You taking over this PR sounds good to me - it would take me some time to find out what renames and reorganizations happened. Thanks!

**Pull request closed without merging**
