### PR TITLE
General modularization, style, and CI cleanup

### PR DESCRIPTION
**Pull request by dgasmith**
This is the generalized module cleanup that I have promised. This is probably just the start, but I didn't want to do sections that were too large at a time. I would recommend looking at the diffs of each commit separately.

The PR will accomplish:
 - [x] Moves OptKing into a folder along with a `setup.py` so that it is installable by Python.
 - [x] Starts a reasonable GitIgnore
 - [x] Updates imports to be Python 3 comparable
 - [x] Ran a static analysis of the code (reading through that could be very useful)
 - [x] README has quick notes on testing and installation.
 - [x] Formatted all of the files.

Please register with [Travis CI](https://travis-ci.org) and [Codecov](https://codecov.io) and flick the OptKing switches to *ON*. Once travis and Codecov is up and running a lot of info about your program will be revealed.

Notes:
 - Please use [YAPF](https://github.com/google/yapf) for file formatting.
 - I added some trivial unit tests for the LJ function, testing needs to be expanded.
 - Since this is Python everything should be snake_case not camelCase.
 - We can re-integrate the Psi4 testing with `pytest` and Travis CI, this would be very useful.
 - Most of your operations can use broadcasting instead of loops, this is highly recommended. See [here](https://eli.thegreenplace.net/2015/broadcasting-arrays-in-numpy/) for a quick tutorial.
 - Much of your `v3d.py` is implemented within NumPy. Whats nice about this is things like `cross`, `atan, etc are implemented in very safe ways. See [here](https://github.com/dgasmith/EEX_scratch/blob/master/eex/energy_eval/geometry.py) for examples.
 - This could use a License so that folks can use it. I would recommend BSD-3C for this project unless you have reservations. Happy to discuss it.

### CODE REVIEW

**Comment by psi-rking** [comment]
I'm glad to hear of the snake_case convention (PEP8, I see).  That's what I am used to from C/C++, but there are high-profile Python style books that use CamelCase, and they got me thinking I ought to.

The license thing I intended to get to.  Will do.

I figured the v3d might placehold for something else eventually.  I know performance doesn't matter (at least I'm assuming it doesn't) in this optimizer, but I'm still reluctant to call a general-order tensor library function for what I know is, e.g., multiply 3 pairs of numbers and add them up.  Perhaps python is sufficiently script-like in its nature that there is not any difference anyway.

**Comment by loriab** [comment]
For another perspective on the NumPy/v3d issue, I once thought similarly that NumPy was overkill and effectively rewrote the libmints `Vector3` class [here](https://github.com/psi4/psi4/blob/master/psi4/driver/qcdb/vecutil.py). I have since decided I was wrong in that since NumPy is ubiquitous and my vecutil is another unreviewed place for error to creep in and weigh down the module. I've been rewriting bits to use np when revisiting parts of code for other reasons. I think especially for pyoptking, where the optimizer alternatives are C++ or SciPy (heavier than NumPy), that it's not bad to go whole hog NumPy like you would BLAS. Just my thoughts.

**Comment by psi-rking** [comment]
The syntax/style-checker is nice!  Quite a few useless end-of-line semi-colons around.  More significiantly, there is a "++cnt" in there - yikes!

**Comment by dgasmith** [comment]
On the camel case thing it mostly depends on where you are coming from. The JS community will lean that way while the C++ will go towards snake case. I highly recommend snake case as the scientific python ecosystem has adopted it and you are more likely to interface to C codes (Psi4). As you mentioned, it is of course PEP8 as well.

**Comment by psi-rking** [comment]
What do you recommend for a license statement (in every file?) ?

I see the whole thing here:
https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29#fulltext

For psi4 we adopted an abbreviated statement.  I'm sure no one wants to give 'legal advice', so maybe it's hard to find an explicit statement of what is sufficient.

**Comment by dgasmith** [comment]
I typically just add a license to the base folder and call it good enough :). Many projects seem to adopt this, realistically it would be difficult to bring legal action one way or another. Hence the recent Google vs Oracle fight. 

-Daniel Smith

**Comment by loriab** [comment]
If you do enough to get GitHub to pick up on the license as the 5th, rightmost icon on the repo, you've probably done enough. Models https://github.com/dgasmith/gau2grid, https://github.com/loriab/pylibefp

**Comment by psi-rking** [comment]
Very good.  I thought the essay at the top of every file was not only annoying, but a very high ratio of words to actual threat.

**Pull request merged**
